---
# tasks/main.yml for user_friendly

- name: "Install user-friendly apt packages"
  ansible.builtin.apt:
    name:
      # General utils
      - htop
      - curl
      - git
      - vim
      - net-tools
      - iotop
      - tmux
      - fzf
      - ripgrep
      - zsh
      - iperf3
      - eza
      - fd-find
      - zoxide
      # Build and debugging tools
      - build-essential
      - cmake
      - gdb
      - strace
      - ltrace
    state: present

- name: "Install Atuin from pre-compiled binary"
  block:
    - name: "Check if atuin is already installed"
      ansible.builtin.stat:
        path: "/usr/local/bin/atuin"
      register: atuin_stat

    - name: "Install atuin if not present"
      when: not atuin_stat.stat.exists
      block:
        - name: "Set atuin architecture fact"
          ansible.builtin.set_fact:
            atuin_arch: "{{ 'aarch64' if ansible_architecture == 'aarch64' else 'x86_64' }}"

        - name: "Download and unarchive Atuin to a temporary directory"
          ansible.builtin.unarchive:
            src: "https://github.com/atuinsh/atuin/releases/latest/download/atuin-{{ atuin_arch }}-unknown-linux-gnu.tar.gz"
            dest: /tmp/
            remote_src: yes
          register: atuin_unarchive_result

        - name: "Copy the atuin binary to the final destination"
          ansible.builtin.copy:
            src: "/tmp/atuin-{{ atuin_arch }}-unknown-linux-gnu/atuin"
            dest: /usr/local/bin/atuin
            mode: '0755'
            remote_src: yes
          when: atuin_unarchive_result.changed

        - name: "Clean up the temporary Atuin directory"
          ansible.builtin.file:
            path: "/tmp/atuin-{{ atuin_arch }}-unknown-linux-gnu"
            state: absent
          when: atuin_unarchive_result.changed
      become: true

- name: Install Google Gemini CLI (Global)
  community.general.npm:
    name: "@google/gemini-cli"
    global: true
    state: latest
  become: true

- name: "Set system timezone"
  community.general.timezone:
    name: "{{ timezone }}"
  when: timezone is defined
