$ANSIBLE_VAULT;1.1;AES256
61613861663037343432663764346333316338303136356564326661613032343231343938323861
3430383437333533656336346233303863353337313435320a663063353664666561316337343735
65653533363238323961613230626632363035343166306635386561626432643464663834393535
3731363838623536380a356363323535326361386537346336343065366166366165306539323236
39393632653638336230383832386662633234393236333231326430336166383436313534666464
3633613538336532626264376137633664626331613232626436
