---
- name: "Ensure target directory exists for cloudflared stack"
  ansible.builtin.file:
    path: "/home/{{ansible_user}}/ansible_docker/cloudflared"
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: '0755'

- name: "Template compose.yaml from j2"
  ansible.builtin.template:
    src: "compose.yaml.j2"
    dest: "/home/{{ansible_user}}/ansible_docker/cloudflared/compose.yaml"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: '0644'
  notify:
    - Restart cloudflared stack

- name: "Create .env file from template"
  ansible.builtin.template:
    src: "env.j2"
    dest: "/home/{{ansible_user}}/ansible_docker/cloudflared/.env"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: '0600' # Secrets file should not be world-readable
  no_log: true
  notify:
    - Restart cloudflared stack

- name: "Deploy the cloudflared docker stack"
  community.docker.docker_compose_v2:
    project_src: "/home/{{ansible_user}}/ansible_docker/cloudflared"
    state: present
